### ISSUE TITLE
AetherOneProcessingV0006.pde (fixed version) crashes

### ISSUE THREAD

**Issue by clifet** [radionics/OpenSourceRadionics#2] opened 2018-07-09 20:03 UTC
The embedded filmclip illustrates the crash, it is already crashing when i start : AetherOneProcessingV0006.pde (fixed version) via the processing software, see clip. After a few minutes the software crashes. After the initiation of the Arduino. 

Video clip 
https://www.dropbox.com/s/l50jwwo7izahtgk/MVI_2067.mp4?dl=0

Error

Arduino found at port COM4
[ARDUINO_PONG]
[AETHER_PING]
[ARDUINO_OK]
[TRNG_START]
controlEvent hotbits
java.lang.ArrayIndexOutOfBoundsException: 61443
at controlP5.ControlWindow.keyEvent(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1408)
at processing.core.PApplet.handleMethods(PApplet.java:1610)
at processing.core.PApplet.handleKeyEvent(PApplet.java:2946)
at processing.core.PApplet.dequeueEvents(PApplet.java:2599)
at processing.core.PApplet.handleDraw(PApplet.java:2437)
at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

<<< SOFTWARE CRASHED (see clip)

**Comment by hydrogen2oxygen** [comment] 2018-07-10 05:49
Hi, don't worry, this is a ControlP5 exception catched by an try&catch block. The AetherOne is still running. You can see that in the video. Please try to broadcast something or click on the GROUNDING button after this "crash" occurs. I expect that it still works. Indeed I have the same error, but this does not stop the program to work.

**Comment by radionics** [comment] 2018-07-10 05:56
Hi, don't worry, this is not a bug of AetherOne, but one of ControlP5 control elements. The program should still work. Can you please check it by clicking on GROUNDING button?

And may I use your video for a FAQ?

**Comment by Hansrik** [comment] 2018-07-10 10:29
Hi,

I will continue the bugreport clifet (thanks) made above, clifet was so kind to post this for me here, cause i had no account to do so. clifet suggested that it would be a good idea to get my own account for future bugs reference etc. 

Radionics, to answer your question:
It is still crashing, and no way to continue clicking on buttons if you wait to long, it crashes... But if you click on the buttons right after the lights went out it will run the program a minute or so and also crashes.
with the same bugreport as stated above.

And yes sure you may use the video for FAQ.

regards
Hans

**Comment by radionics** [comment] 2018-07-10 10:57
Could you please post the entire error message from the crash? It seems that there is more and I need it to recognize the part of the software where the crash occurs.

And did this error occur only since the version "Version 0006 fixed"?

**Comment by Hansrik** [comment] 2018-07-10 11:28
Hi Radionics,

> And did this error occur only since the version "Version 0006 fixed"?> 

NO the older 0006 same report.
I will paste both bug reports (the old and the fixed one)



**AetherOneProcessingV0006.pde (OLD)**

there are 0 lines
We have now 0 hot seeds!
getPort 0 of 3
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
controlEvent clear
controlEvent grounding
controlEvent connect
controlEvent select data
controlEvent analyze
controlEvent general vitality
controlEvent broadcast
jul 10, 2018 1:08:49 PM controlP5.ControlBroadcaster invokeMethod
WARNING: java.lang.IllegalArgumentException: wrong number of arguments
controlEvent disconnect
controlEvent progress
controlEvent progress
controlEvent hotbits
controlEvent hotbits
controlEvent Max Hits
controlEvent Broadcast Repeats
controlEvent Delay
controlEvent hotbits
getPort 1 of 3
getPort 2 of 3
Port COM4 is not a arduino.
[B6]
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Arduino found at port COM4
[ARDUINO_PONG]
[AETHER_PING]
[ARDUINO_OK]
[TRNG_START]
controlEvent hotbits
controlEvent hotbits
controlEvent hotbits
java.lang.ArrayIndexOutOfBoundsException: 61443
	at controlP5.ControlWindow.keyEvent(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1408)
	at processing.core.PApplet.handleMethods(PApplet.java:1610)
	at processing.core.PApplet.handleKeyEvent(PApplet.java:2946)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2599)
	at processing.core.PApplet.handleDraw(PApplet.java:2437)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

### 

**AetherOneProcessingV0006.pde (FIXED)**

there are 133267 lines
We have now 133267 hot seeds!
getPort 0 of 3
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
controlEvent clear
controlEvent grounding
controlEvent connect
controlEvent select data
controlEvent analyze
controlEvent general vitality
controlEvent broadcast
jul 10, 2018 1:13:26 PM controlP5.ControlBroadcaster invokeMethod
WARNING: java.lang.IllegalArgumentException: wrong number of arguments
controlEvent disconnect
controlEvent progress
controlEvent progress
controlEvent hotbits
controlEvent hotbits
controlEvent Max Hits
controlEvent Broadcast Repeats
controlEvent Delay
controlEvent hotbits
getPort 1 of 3
getPort 2 of 3
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Port COM4 is not a arduino.
Arduino found at port COM4
[ARDUINO_PONG]
[AETHER_PING]
[ARDUINO_OK]
[TRNG_START]
controlEvent hotbits
controlEvent hotbits
controlEvent hotbits
controlEvent hotbits
java.lang.ArrayIndexOutOfBoundsException: 61443
	at controlP5.ControlWindow.keyEvent(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1408)
	at processing.core.PApplet.handleMethods(PApplet.java:1610)
	at processing.core.PApplet.handleKeyEvent(PApplet.java:2946)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2599)
	at processing.core.PApplet.handleDraw(PApplet.java:2437)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

regards
Hans

**Comment by radionics** [comment] 2018-07-10 14:01
Which version of Processing do you use?
I have the 3.3.7.

And have you uploaded the most current version of the Arduino Software to your microcontroller?
Which model do you use and which software for the Arduino has you uploaded?

**Comment by Hansrik** [comment] 2018-07-10 16:39
Hi Radionics

**Which version of Processing do you use? I have the 3.3.7.**
Hans: i use Processing version: 3.3.7

**And have you uploaded the most current version of the Arduino Software to your microcontroller?**
Hans: i use 1.8.5 for uploading the AetherOneForArduinoUno.ino (hope this is the most current)

**Which model do you use and which software for the Arduino has you uploaded?**
Do you mean the programmer? : i use the default AVRISP mkII
I use the Arduino UNO Rev3

regards
Hans

**Comment by radionics** [comment] 2018-07-11 06:11
I'm sorry, it seems to be a bug of the ControlP5 element, see [https://github.com/sojamo/controlp5/issues/127](https://github.com/sojamo/controlp5/issues/127). The author of ControlP5 says that it was fixed with version 2.2.6. I need to fork his code and see if I can find the bug. Stay tuned and thanks for reporting the issue.

**Comment by Hansrik** [comment] 2018-07-11 08:54
Hi Radionics,

Thanks

regards
Hans

**Comment by radionics** [comment] 2018-07-11 08:54
I forgot to ask about your JVM (Java Version) and your Operating System. Do you use Windows? If yes, I can upload a modified version of ControlP5 which you can replace inside your processing. This will help to identify the error and a possible solution.

**Comment by Hansrik** [comment] 2018-07-11 08:56
I have the latest Java  Version 8 Update 17 Releasedate 17 april 2018 
i use Windows 10

**Comment by Hansrik** [comment] 2018-07-11 08:57
Yes please, let me know how i can help

regards
Hans

**Comment by radionics** [comment] 2018-07-11 11:04
Hi,

you can download here the modified controlP5.jar
https://drive.google.com/open?id=1pZGR93twcDwK9r2FZjueKFSdMlTe2E7T

Stop first Processing IDE and replace it with the jar inside of  Documents\Processing\libraries\controlP5\library

![image](https://user-images.githubusercontent.com/31007091/42567668-c8ae4ce0-850a-11e8-91d5-1f6fd4bf076d.png)

Then restart Processing please.

**Comment by Hansrik** [comment] 2018-07-11 11:22
Hi Radionics,

Thanks i will do some tests now, will report back.

regards
Hans

**Comment by Stellaki** [comment] 2018-07-11 19:01
hi Hans, 
Are you Willie Wortel?

**Comment by Hansrik** [comment] 2018-07-11 21:19
Hi Stellaki,

Yes i call myself Willie Wortel @ facebook

regards
Hans

**Comment by radionics** [comment] 2018-07-12 06:00
I made a pull request to the original project of ControlP5: https://github.com/sojamo/controlp5/pull/128
and I will close this issue.

**Closed by radionics** 2018-07-12 06:00 UTC
Labels: bug
